name: book_recommender
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - geopandas=0.10.2
  - jupyter=1.0.0
  - jupyterlab=3.2.4
  - matplotlib=3.5.0
  - seaborn=0.11.2
  - gdown=4.2.0
  - pycountry=20.7.3
  - python-dotenv=0.19.2
  - langcodes=3.3.0
  - pandas=1.3.4
  - neptune-client=0.13.3
  - optuna=2.10.0
  - pymysql=1.0.2
  - graphviz=2.50.0
  - pydot=1.4.2
  - tensorflow=2.6.0
  - neptune-tensorflow-keras=0.9.9
  - treelib=1.6.1
  - lxml=4.7.1
  - pip:
    - countryinfo==0.1.2
    - isbnlib==3.10.9
    - language-data==1.1
    - marisa-trie==0.7.7
